package cis232.semesterproject.brewer;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class CraftBeerDB {

	public static void main(String[] args) {
			Connection conn = null;
			Statement stmt = null;
			
			//Initialize DB Connection and create statement
			try{
				conn = DriverManager.getConnection("jdbc:derby:db/Beers; create=true");
				System.out.println("Connection Initialized");
				stmt = conn.createStatement();
			}catch(SQLException e){
				System.out.printf("DB Error %s: ", e.getMessage());
				e.printStackTrace();
			}
			
			//Drops table if already exists
			try{
				String dropTable = "drop Table CraftBeers";
				stmt.execute(dropTable);
				System.out.println("Craft Beers table dropped");
			}catch(SQLException e){
				System.out.println("Craft Beers table doesn't exist");
			}
			
			//Create table string
			String createBeersTable = "create table CraftBeers(" +
						"id int NOT NULL GENERATED BY DEFAULT AS IDENTITY, " + 
						"name varchar(100), " +
						"grains varchar(50), " +
						"yeast varchar(50), " +
						"hops varchar(50), " +
						"special varchar(500), " +
						"primary key(id)" +
						")";
			
			//Execute table creation
			try{
				stmt.execute(createBeersTable);
				System.out.println("Craft Beers table created.");
			} catch(SQLException e){
				System.out.printf("Error creating Craft Beers table: %s", e.getMessage());
			}
			
			
			/**
			 * Add Craft Beers Below
			 */
			addCraftBeer(conn,"I dont even know","Stuff","More Stuff","Something normal","A bunch of random ingredients");
		}
		
		public static void addCraftBeer(Connection conn, String name, String grains, String yeast, String hops, String Special){
			Statement stmt = null;
			try{
				stmt = conn.createStatement();
				
				String insertBeer = String.format("Insert Into CraftBeers (name, grains, yeast, hops, special)" +
													" values('%s', '%s', '%s', '%s', '%s')", name, grains, yeast, hops, Special);
				stmt.execute(insertBeer);
				System.out.printf("%s added %n", name);
			}catch(SQLException | NumberFormatException e){
				System.out.printf("Error adding beer: %s", e.getMessage());
			}
		}
}
