package cis232.semesterproject.brewer;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class PureBeerDB{

	public static void main(String[] args) {
		Connection conn = null;
		Statement stmt = null;
		
		//Initialize DB Connection and create statement
		try{
			conn = DriverManager.getConnection("jdbc:derby:db/Beers; create=true");
			System.out.println("Connection Initialized");
			stmt = conn.createStatement();
		}catch(SQLException e){
			System.out.printf("DB Error %s: ", e.getMessage());
			e.printStackTrace();
		}
		
		//Drops table if already exists
		try{
			String dropTable = "drop Table PureBeers";
			stmt.execute(dropTable);
			System.out.println("Pure Beers table dropped");
		}catch(SQLException e){
			System.out.println("Pure Beers table doesn't exist");
		}
		
		//Create table string
		String createBeersTable = "create table PureBeers(" +
							"id int NOT NULL GENERATED BY DEFAULT AS IDENTITY, " + 
							"name varchar(100), " +
							"grains varchar(50), " +
							"yeast varchar(50), " +
							"hops varchar(50), " +
							"primary key(id)" +
							")";
		
		//Execute table creation
		try{
			stmt.execute(createBeersTable);
			System.out.println("Pure Beers table created.");
		} catch(SQLException e){
			System.out.printf("Error creating Beers table: %s", e.getMessage());
		}
		
		/**
		 * Add Pure Beers Below
		 */
		addPureBeer(conn, "Saison", "6-row", "Wyeast1056", "Fuggle");
		addPureBeer(conn, "Porter", "2-row", "US-05", "Saaz");
		addPureBeer(conn, "PaleAle", "Pilsen", "WLP566", "Cascade");
		addPureBeer(conn, "BarleyWine", "Crystal", "Wyeast1084", "Columbus");
		addPureBeer(conn, "Stout", "Wheat", "Wyeast1764", "Calypso");
		addPureBeer(conn, "Test_Name", "Test_Grain", "Test_Yeast", "Test_Hops");
	}
	
	public static void addPureBeer(Connection conn, String name, String grains, String yeast, String hops){
		Statement stmt = null;
		try{
			stmt = conn.createStatement();
			
			String insertBeer = String.format("Insert Into PureBeers (name, grains, yeast, hops)" +
												" values('%s', '%s', '%s', '%s')",
												  name, grains, yeast, hops);
			stmt.execute(insertBeer);
			System.out.printf("%s added %n", name);
		}catch(SQLException | NumberFormatException e){
			System.out.printf("Error adding beer: %s", e.getMessage());
		}
	}
}
